USE BETES;

INSERT INTO `UTILISATEUR` (`NOM`, `PRENOM`, `PSEUDO`, `DATE_NAISSANCE`, `PASSWORD`, `ROLE`) VALUES
('DUMAS', 'Thibault', 'Thibalti', '1985-07-31', 'ToTo123', 'ADMIN');

INSERT INTO `UTILISATEUR` (`NOM`, `PRENOM`, `PSEUDO`, `DATE_NAISSANCE`, `PASSWORD`, `ROLE`) VALUES
('VILLE', 'Florian', 'Florian', '1992-10-19', 'root', 'ADMIN');

INSERT INTO `UTILISATEUR` (`NOM`, `PRENOM`, `PSEUDO`, `DATE_NAISSANCE`, `PASSWORD`, `ROLE`) VALUES
('ELWERT', 'Aline', 'Akawe', '1993-05-28-', 'root', 'ADMIN');

INSERT INTO `UTILISATEUR` (`NOM`, `PRENOM`, `PSEUDO`, `DATE_NAISSANCE`, `PASSWORD`, `ROLE`) VALUES
('BOUDOU', 'Nathan', 'Boudoudou', '1999-01-25', 'root', 'ADMIN');

INSERT INTO `UTILISATEUR` (`NOM`, `PRENOM`, `PSEUDO`, `DATE_NAISSANCE`, `PASSWORD`, `ROLE`) VALUES
('AUBRY', 'Camille', 'Camou', '1993-04-19', 'root', 'ADMIN');