USE betes;

DROP TABLE IF EXISTS `EQUIPE`;
CREATE TABLE `EQUIPE`(
`ID_EQUIPE` BIGINT (20) NOT NULL AUTO_INCREMENT
, `ID_JEUX` BIGINT (20) NOT NULL
, `NOM_EQUIPE` VARCHAR (50) NOT NULL
, `LOGO` BLOB
, `ID_API_EXTERNE` INTEGER (10) NOT NULL
, PRIMARY KEY (`ID_EQUIPE`)
, UNIQUE KEY `ID_API_EXTERNE_UNIQUE` (`ID_API_EXTERNE`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;