USE BETES;

DROP TABLE IF EXISTS `MATCH`;
CREATE TABLE `MATCH` (
`ID_MATCH` BIGINT (20) NOT NULL AUTO_INCREMENT
, `NOM_JEU` VARCHAR (50) NOT NULL
, `DATE_MATCH` TIMESTAMP
, `VAINQUEUR` VARCHAR (50)
, `ID_API_EXTERNE` INTEGER (10) NOT NULL
, PRIMARY KEY (`ID_MATCH`)
, UNIQUE KEY `ID_API_EXTERNE_UNIQUE` (`ID_API_EXTERNE`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;