USE BETES;

DROP TABLE IF EXISTS `PARIS`;
CREATE TABLE `PARIS` (
`ID_PARIS` BIGINT (20) NOT NULL AUTO_INCREMENT
, `ID_UTILISATEUR` BIGINT (20) NOT NULL
, `ID_MATCH` BIGINT (20) NOT NULL
, `VAINQUEUR` BIGINT (20) NOT NULL
, `DATE_PARI` DATE NOT NULL
, `RESULTAT_PARI` BOOLEAN
, `DATE_UPDATE` DATE
, PRIMARY KEY (`ID_PARIS`)
, UNIQUE KEY `PARI_UNIQUE` (`ID_UTILISATEUR`, `ID_MATCH`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;