-- CREATE SCHEMA BETES;

USE BETES;

DROP TABLE IF EXISTS `UTILISATEUR`;
CREATE TABLE `UTILISATEUR`(
`ID_UTILISATEUR` BIGINT (20) NOT NULL AUTO_INCREMENT
, `NOM` VARCHAR (50) NOT NULL
, `PRENOM` VARCHAR (50) NOT NULL
, `PSEUDO` VARCHAR (50) NOT NULL
, `DATE_NAISSANCE` DATE NOT NULL
, `PASSWORD` VARCHAR (50) NOT NULL
, `ROLE` VARCHAR (20) NOT NULL DEFAULT 'USER'
, `DATE_INSCRIPTION` DATETIME DEFAULT CURRENT_TIMESTAMP
, `VALIDATION_INSCRIPTION` BOOLEAN NOT NULL DEFAULT '1'
, PRIMARY KEY (`ID_UTILISATEUR`)
, UNIQUE KEY `PSEUDO_UNIQUE` (`PSEUDO`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;